### ISSUE TITLE
[Bug/Integration] `Neo4jMemoryService` (Google ADK) is incompatible with NAMS backend + v0.4 documentation Mismatches

### ISSUE THREAD

**Issue by kaustubh-darekar** [neo4j-labs/agent-memory#130]
### Description
There are critical compatibility issues when attempting to use the newly hosted NAMS backend (`v0.4.0`) in conjunction with the Google ADK integration (`Neo4jMemoryService`). 

Additionally, there are discrepancies between the v0.4 migration documentation and the underlying SDK method signatures that cause crashes during manual implementations.

---

### Part 1: `Neo4jMemoryService` breaks with `backend="nams"`

**1. `search_memory` omits mandatory `session_id`**
The `Neo4jMemoryService.search_memory()` method calls the underlying client's `search_messages` without passing a `session_id`. 

**The Bug:** While this works on the local Bolt backend, NAMS v0.4 strictly enforces conversation-scoped searches.
**The Result:** When the ADK `LoadMemoryTool` fires, the application hard-crashes with:
  `ValueError: search_messages requires session_id on NAMS — the API is conversation-scoped...`

**2. `add_session_to_memory` pushes stringified Function/Tool objects to NAMS**
The ADK `Session` object stores all events, including `FunctionCall` and `FunctionResponse` objects. 

**The Bug:** Inside `memory_service.py`, the `_extract_text_from_content` method attempts to pull text from parts, but falls back to `str(content)`. This stringifies raw JSON/Python tool-call objects and pushes them to NAMS as standard chat messages via `add_message()`.
**The Result:** The NAMS cloud background GraphRAG pipeline fails to parse the stringified JSON noise, resulting in empty Entity graphs despite "HTTP 201 Created" logs.

---

### Part 2: SDK Signature vs Documentation Mismatches
For users attempting to bypass the broken ADK wrapper and write manual clients, the v0.4 SDK signatures conflict directly with the official documentation.

**1. `add_message()`: `session_id` vs `conversation_id`**
The documentation explicitly instructs developers to use `conversation_id`:
`await client.short_term.add_message(conversation_id, "user", "Hello!")`

**The Bug:** Using keyword arguments (e.g., `add_message(conversation_id=conv.id)`) throws a `TypeError: missing 1 required positional argument: 'session_id'` because the underlying Python signature never updated its parameter name.

**2. `add_entity()`: `label` vs `entity_type`**
The documentation refers to entity classifications as `type` or `label`.

**The Bug:** `NamsLongTermMemory.add_entity()` strictly requires the keyword `entity_type`. Using legacy kwargs causes a `TypeError`.

---

### Proposed Solutions

- [ ] **Patch `Neo4jMemoryService`:** Update the ADK wrapper to accept and pass the active `session_id` downward during `search_memory`, and strictly filter out non-text tool events inside `_extract_messages()`.

- [ ] **Standardize NAMS Signatures:** Either align the `nams/short_term.py` parameters to match the documentation (`conversation_id`), or update the docs to explicitly enforce the use of the legacy `session_id` parameter. Standardize the positional order of arguments across the CRUD methods.

**Comment by kaustubh-darekar** [comment]
Also if we try to integrate neo4jMemoryService with ADK using NAMS it fails to retrieve and ingest.

Code to reproduce.

```python
import asyncio
import os
from pydantic import SecretStr
from google.genai import types
from google.adk.agents.llm_agent import LlmAgent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.artifacts.in_memory_artifact_service import InMemoryArtifactService
from neo4j_agent_memory import MemoryClient, MemorySettings, NamsConfig
from neo4j_agent_memory.integrations.google_adk import Neo4jMemoryService
from google.adk.tools.load_memory_tool import LoadMemoryTool
from dotenv import load_dotenv
load_dotenv()
MEMORY_API_KEY = os.environ.get("MEMORY_API_KEY")
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")

if "MEMORY_API_KEY" not in os.environ:
    os.environ["MEMORY_API_KEY"] = getpass("Enter NAMS API Key: ")

async def run_nams_adk_repro():
    # 1. Setup NAMS backend
    settings = MemorySettings(
        backend="nams",
        nams=NamsConfig(api_key=SecretStr(os.environ["MEMORY_API_KEY"]), validate_on_connect=False)
    )
    client = MemoryClient(settings)
    await client.connect()

    # 2. Wrap in official ADK Memory Service
    adk_memory = Neo4jMemoryService(memory_client=client, user_id="tester")

    # 3. Setup standard ADK Agent & Runner
    agent = LlmAgent(
        model=os.environ.get("GEMINI_MODEL", "gemini-2.5-flash"),
        name="assistant",
        instruction="You are an AI with memory. Use the load_memory tool to recall facts.",
        tools=[LoadMemoryTool()]
    )

    session_service = InMemorySessionService()
    session = await session_service.create_session(session_id="nams_test_thread", state={}, app_name="test", user_id="tester")

    runner = Runner(
        app_name="test",
        agent=agent,
        artifact_service=InMemoryArtifactService(),
        session_service=session_service,
        memory_service=adk_memory
    )

    # STEP 1: Ask it to remember (Runner auto-calls add_session_to_memory at the end)
    print("--- STEP 1: Ingestion ---")
    msg1 = types.Content(role='user', parts=[types.Part(text="Remember that my favorite coding language is Python.")])
    try:
        async for _ in runner.run_async(session_id=session.id, user_id=session.user_id, new_message=msg1):
            pass
    except Exception as e:
        print(f"Step 1 Failed: {type(e).__name__}: {e}")

    # STEP 2: Ask it to retrieve (Triggers LoadMemoryTool -> search_memory)
    print("\n--- STEP 2: Retrieval ---")
    msg2 = types.Content(role='user', parts=[types.Part(text="What is my favorite coding language?")])
    try:
        async for _ in runner.run_async(session_id=session.id, user_id=session.user_id, new_message=msg2):
            pass
    except Exception as e:
        print(f"Error: {type(e).__name__}: {e}")

# Run in notebook
await run_nams_adk_repro()```
